image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build
    init: |
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - ionide.ionide-fsharp
    - muhammad-sammy.csharp
